# Generated by Django 5.2.15 on 2026-06-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custom_id', models.CharField(blank=True, max_length=15)),
                ('Company_name', models.CharField(blank=True, max_length=150)),
                ('Description', models.TextField(blank=True)),
                ('Enquiry_date', models.DateField(blank=True, null=True)),
                ('Closing_date', models.DateField(blank=True, null=True)),
                ('Enquiry_type', models.CharField(blank=True, max_length=50)),
                ('Admin_remark', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry_email_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.TextField(blank=True)),
                ('Time', models.DateTimeField(blank=True, null=True)),
                ('Enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enquiry_email_messages', to='enquiry.enquiry_details')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.FileField(blank=True, null=True, upload_to='Enquiry_documents/')),
                ('Image', models.FileField(blank=True, null=True, upload_to='Enquiry_images/')),
                ('Enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enquiry_media', to='enquiry.enquiry_details')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sector', models.CharField(blank=True, max_length=100)),
                ('Division', models.CharField(blank=True, max_length=100)),
                ('Product_group', models.CharField(blank=True, max_length=100)),
                ('Product_category', models.CharField(blank=True, max_length=100)),
                ('Product', models.CharField(blank=True, max_length=100)),
                ('HSN_code', models.CharField(blank=True, max_length=10)),
                ('Billing_address', models.TextField(blank=True)),
                ('Delivery_address', models.TextField(blank=True)),
                ('Quantity', models.CharField(blank=True, max_length=20)),
                ('Packaging', models.CharField(blank=True, max_length=200)),
                ('Target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Currency', models.CharField(blank=True, choices=[('AFN', 'Afn'), ('ALL', 'All'), ('DZD', 'Dzd'), ('USD', 'Usd'), ('EUR', 'Eur'), ('AOA', 'Aoa'), ('XCD', 'Xcd'), ('ren', 'Ren'), ('ARS', 'Ars'), ('AMD', 'Amd'), ('AWG', 'Awg'), ('AUD', 'Aud'), ('AZN', 'Azn'), ('BSD', 'Bsd'), ('BHD', 'Bhd'), ('BDT', 'Bdt'), ('BBD', 'Bbd'), ('BYN', 'Byn'), ('BZD', 'Bzd'), ('XOF', 'Xof'), ('BMD', 'Bmd'), ('BTN', 'Btn'), ('INR', 'Inr'), ('BOB', 'Bob'), ('BOV', 'Bov'), ('BAM', 'Bam'), ('BWP', 'Bwp'), ('NOK', 'Nok'), ('BRL', 'Brl'), ('BND', 'Bnd'), ('BIF', 'Bif'), ('CVE', 'Cve'), ('KHR', 'Khr'), ('XAF', 'Xaf'), ('CAD', 'Cad'), ('KYD', 'Kyd'), ('CLF', 'Clf'), ('CLP', 'Clp'), ('CNY', 'Cny'), ('COP', 'Cop'), ('COU', 'Cou'), ('KMF', 'Kmf'), ('CDF', 'Cdf'), ('NZD', 'Nzd'), ('CRC', 'Crc'), ('CUC', 'Cuc'), ('CUP', 'Cup'), ('XCG', 'Xcg'), ('CZK', 'Czk'), ('DKK', 'Dkk'), ('DJF', 'Djf'), ('DOP', 'Dop'), ('EGP', 'Egp'), ('SVC', 'Svc'), ('ERN', 'Ern'), ('ETB', 'Etb'), ('FKP', 'Fkp'), ('FJD', 'Fjd'), ('XPF', 'Xpf'), ('GMD', 'Gmd'), ('GEL', 'Gel'), ('GHS', 'Ghs'), ('GIP', 'Gip'), ('GTQ', 'Gtq'), ('GBP', 'Gbp'), ('GNF', 'Gnf'), ('GYD', 'Gyd'), ('HTG', 'Htg'), ('HNL', 'Hnl'), ('HKD', 'Hkd'), ('HUF', 'Huf'), ('ISK', 'Isk'), ('IDR', 'Idr'), ('XDR', 'Xdr'), ('IRR', 'Irr'), ('IQD', 'Iqd'), ('ILS', 'Ils'), ('JMD', 'Jmd'), ('JPY', 'Jpy'), ('JOD', 'Jod'), ('KZT', 'Kzt'), ('KES', 'Kes'), ('KPW', 'Kpw'), ('KRW', 'Krw'), ('KWD', 'Kwd'), ('KGS', 'Kgs'), ('LAK', 'Lak'), ('LBP', 'Lbp'), ('LSL', 'Lsl'), ('ZAR', 'Zar'), ('LRD', 'Lrd'), ('LYD', 'Lyd'), ('CHF', 'Chf'), ('MOP', 'Mop'), ('MGA', 'Mga'), ('MWK', 'Mwk'), ('MYR', 'Myr'), ('MVR', 'Mvr'), ('MRU', 'Mru'), ('MUR', 'Mur'), ('XUA', 'Xua'), ('MXN', 'Mxn'), ('MXV', 'Mxv'), ('MDL', 'Mdl'), ('MNT', 'Mnt'), ('MAD', 'Mad'), ('MZN', 'Mzn'), ('MMK', 'Mmk'), ('NAD', 'Nad'), ('NPR', 'Npr'), ('NIO', 'Nio'), ('NGN', 'Ngn'), ('OMR', 'Omr'), ('PKR', 'Pkr'), ('PAB', 'Pab'), ('PGK', 'Pgk'), ('PYG', 'Pyg'), ('PEN', 'Pen'), ('PHP', 'Php'), ('PLN', 'Pln'), ('QAR', 'Qar'), ('MKD', 'Mkd'), ('RON', 'Ron'), ('RUB', 'Rub'), ('RWF', 'Rwf'), ('SHP', 'Shp'), ('WST', 'Wst'), ('STN', 'Stn'), ('SAR', 'Sar'), ('RSD', 'Rsd'), ('SCR', 'Scr'), ('SLE', 'Sle'), ('SGD', 'Sgd'), ('XSU', 'Xsu'), ('SBD', 'Sbd'), ('SOS', 'Sos'), ('SSP', 'Ssp'), ('LKR', 'Lkr'), ('SDG', 'Sdg'), ('SRD', 'Srd'), ('SZL', 'Szl'), ('SEK', 'Sek'), ('CHE', 'Che'), ('CHW', 'Chw'), ('SYP', 'Syp'), ('TWD', 'Twd'), ('TJS', 'Tjs'), ('TZS', 'Tzs'), ('THB', 'Thb'), ('TOP', 'Top'), ('TTD', 'Ttd'), ('TND', 'Tnd'), ('TRY', 'Try'), ('TMT', 'Tmt'), ('UGX', 'Ugx'), ('UAH', 'Uah'), ('AED', 'Aed'), ('USN', 'Usn'), ('UYI', 'Uyi'), ('UYU', 'Uyu'), ('UZS', 'Uzs'), ('VUV', 'Vuv'), ('VEF', 'Vef'), ('VED', 'Ved'), ('VND', 'Vnd'), ('YER', 'Yer'), ('ZMW', 'Zmw'), ('ZWL', 'Zwl'), ('uro', 'Uro')], max_length=5)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Enquiry_products', to='enquiry.enquiry_details')),
            ],
        ),
    ]
