# Generated by Django 5.2.15 on 2026-06-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer_details_created_at_buyer_details_custom_id'),
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_details',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Enquiry_details', to='buyer.buyer_details'),
        ),
    ]
