# Generated by Django 5.2.15 on 2026-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_enquiry_details_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry_email_messages',
            old_name='Email',
            new_name='Body',
        ),
        migrations.AddField(
            model_name='enquiry_email_messages',
            name='Subject',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enquiry_email_messages',
            name='To',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
