# Generated by Django 5.2.15 on 2026-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_rename_email_enquiry_email_messages_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_products',
            name='Currency',
            field=models.CharField(blank=True, choices=[], max_length=5),
        ),
    ]
