# Generated by Django 5.2.15 on 2026-07-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_alter_enquiry_products_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_products',
            name='Currency',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
