# Generated by Django 5.2.15 on 2026-07-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_alter_enquiry_products_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry_products',
            old_name='Supplier',
            new_name='Enquiry',
        ),
    ]
