# Generated by Django 5.2.15 on 2026-06-30 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(blank=True, max_length=150)),
                ('Description', models.TextField(blank=True)),
                ('Website_link', models.CharField(blank=True, max_length=100)),
                ('GST_number', models.CharField(blank=True, max_length=20)),
                ('IEC_code', models.CharField(blank=True, max_length=15)),
                ('PAN_number', models.CharField(blank=True, max_length=15)),
                ('DIN_number', models.CharField(blank=True, max_length=25)),
                ('CIN_number', models.CharField(blank=True, max_length=30)),
                ('DB_number', models.CharField(blank=True, max_length=30)),
                ('Contact_person', models.CharField(blank=True, max_length=100)),
                ('Payment_terms', models.TextField(blank=True)),
                ('Supplier_preferences', models.TextField(blank=True)),
                ('Transport_preferences', models.TextField(blank=True)),
                ('Monthly_requirements', models.TextField(blank=True)),
                ('Admin_remark', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer_contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Phone', models.CharField(blank=True, max_length=20)),
                ('Note', models.TextField(blank=True)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer_contact_details', to='buyer.buyer_details')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer_addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField(blank=True)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('State', models.CharField(blank=True, max_length=50)),
                ('Country', models.CharField(blank=True, max_length=50)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer_addresses', to='buyer.buyer_details')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer_email_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.TextField(blank=True)),
                ('Time', models.DateTimeField(blank=True, null=True)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer_email_messages', to='buyer.buyer_details')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.FileField(blank=True, null=True, upload_to='Buyer_documents/')),
                ('Image', models.FileField(blank=True, null=True, upload_to='Buyer_images/')),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Buyer_media', to='buyer.buyer_details')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sector', models.CharField(blank=True, max_length=100)),
                ('Division', models.CharField(blank=True, max_length=100)),
                ('Product_group', models.CharField(blank=True, max_length=100)),
                ('Product_category', models.CharField(blank=True, max_length=100)),
                ('Product', models.CharField(blank=True, max_length=100)),
                ('HSN_code', models.CharField(blank=True, max_length=10)),
                ('Billing_address', models.TextField(blank=True)),
                ('Delivery_address', models.TextField(blank=True)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Purchase_products', to='buyer.buyer_details')),
            ],
        ),
    ]
