# Generated by Django 5.2.15 on 2026-06-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_details',
            name='Created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer_details',
            name='Custom_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
