# Generated by Django 5.2.15 on 2026-07-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_rename_email_buyer_email_messages_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer_details',
            old_name='DB_number',
            new_name='DUNS_number',
        ),
    ]
