# Generated by Django 5.2.15 on 2026-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_rename_db_number_buyer_details_duns_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_details',
            name='WCPD_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
