# Generated by Django 5.2.15 on 2026-07-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_buyer_details_wcpd_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_contact_details',
            name='Note',
        ),
    ]
