# Generated by Django 5.2.15 on 2026-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_remove_buyer_contact_details_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_contact_details',
            name='FAX',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
