# Generated by Django 5.2.15 on 2026-07-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_buyer_contact_details_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_email_messages',
            name='From',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
