# Generated by Django 5.2.15 on 2026-06-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custom_id', models.CharField(blank=True, max_length=15)),
                ('Company_name', models.CharField(blank=True, max_length=150)),
                ('Description', models.TextField(blank=True)),
                ('Website_link', models.CharField(blank=True, max_length=100)),
                ('GST_number', models.CharField(blank=True, max_length=20)),
                ('IEC_code', models.CharField(blank=True, max_length=15)),
                ('PAN_number', models.CharField(blank=True, max_length=15)),
                ('DIN_number', models.CharField(blank=True, max_length=25)),
                ('CIN_number', models.CharField(blank=True, max_length=30)),
                ('DB_number', models.CharField(blank=True, max_length=30)),
                ('Contact_person', models.CharField(blank=True, max_length=100)),
                ('wcpd_code', models.CharField(blank=True, max_length=10)),
                ('Admin_remark', models.TextField(blank=True)),
                ('FAX', models.CharField(blank=True, max_length=15)),
                ('Created_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='supplier_contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Phone', models.CharField(blank=True, max_length=20)),
                ('Note', models.TextField(blank=True)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_contact_details', to='supplier.supplier_details')),
            ],
        ),
        migrations.CreateModel(
            name='supplier_addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.TextField(blank=True)),
                ('City', models.CharField(blank=True, max_length=50)),
                ('State', models.CharField(blank=True, max_length=50)),
                ('Country', models.CharField(blank=True, max_length=50)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_addresses', to='supplier.supplier_details')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sector', models.CharField(blank=True, max_length=100)),
                ('Division', models.CharField(blank=True, max_length=100)),
                ('Product_group', models.CharField(blank=True, max_length=100)),
                ('Product_category', models.CharField(blank=True, max_length=100)),
                ('Product', models.CharField(blank=True, max_length=100)),
                ('HSN_code', models.CharField(blank=True, max_length=10)),
                ('Factory_address', models.TextField(blank=True)),
                ('Warehouse_address', models.TextField(blank=True)),
                ('Min_order_quantity', models.CharField(blank=True, max_length=30)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sell_products', to='supplier.supplier_details')),
            ],
        ),
        migrations.CreateModel(
            name='supplier_email_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.TextField(blank=True)),
                ('Time', models.DateTimeField(blank=True, null=True)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_email_messages', to='supplier.supplier_details')),
            ],
        ),
        migrations.CreateModel(
            name='supplier_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.FileField(blank=True, null=True, upload_to='Supplier_documents/')),
                ('Image', models.FileField(blank=True, null=True, upload_to='Supplier_images/')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_media', to='supplier.supplier_details')),
            ],
        ),
    ]
