# Generated by Django 5.2.15 on 2026-07-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_details',
            old_name='wcpd_code',
            new_name='WCPD_code',
        ),
    ]
