# Generated by Django 5.2.15 on 2026-07-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_rename_wcpd_code_supplier_details_wcpd_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_details',
            old_name='DB_number',
            new_name='DUNS_number',
        ),
    ]
