# Generated by Django 5.2.15 on 2026-07-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_rename_db_number_supplier_details_duns_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_details',
            name='FAX',
        ),
        migrations.AddField(
            model_name='supplier_contact_details',
            name='FAX',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
