# Generated by Django 5.2.15 on 2026-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_supplier_details_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_products',
            name='Product',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
