# Generated by Django 5.2.15 on 2026-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_sell_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_contact_details',
            name='Note',
        ),
        migrations.AlterField(
            model_name='supplier_contact_details',
            name='FAX',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='supplier_contact_details',
            name='Phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
