# Generated by Django 5.2.15 on 2026-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_remove_supplier_contact_details_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_email_messages',
            old_name='Email',
            new_name='Body',
        ),
        migrations.AddField(
            model_name='supplier_email_messages',
            name='Subject',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier_email_messages',
            name='To',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
