# Generated by Django 5.2.15 on 2026-07-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_rename_email_supplier_email_messages_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_products',
            name='Product_group',
            field=models.CharField(blank=True, choices=[('FCSL', 'Fcsl'), ('ICSL', 'Icsl'), ('FCCL', 'Fccl'), ('ICCL', 'Iccl'), ('FCSC', 'Fcsc'), ('ICSC', 'Icsc'), ('DCSC', 'Dcsc'), ('DCSL', 'Dcsl')], max_length=10),
        ),
    ]
