# Generated by Django 5.2.15 on 2026-07-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_alter_sell_products_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_products',
            name='Product_group',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
