# Generated by Django 5.2.15 on 2026-07-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0010_alter_sell_products_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_email_messages',
            name='From',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
